version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: stydedocker/app
    volumes:
      - .:/var/www/html
    networks:
      - stydenet
  node:
    image: node:9.8
    volumes:
      - .:/var/www/html
    networks:
      - stydenet
  redis:
    image: redis:alpine
    networks:
      - stydenet
networks:
  stydenet:
    driver: "bridge"
